services:
  fmt-got:
    build: .
    environment:
      - FLAG=${FLAG}
      - PORT=1337
    expose:
      - "1337"
    labels:
      - "owl.proxy=true"
      - "owl.proxy.port=1337"
      - "owl.label.conntype=nc"
      - "owl.label.comment=fmt-got service"
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    external: true
    name: ctfd_frp_containers
